//! Bitmap fonts for braille canvases; see [`Font`].

use std::fmt;
use std::sync::OnceLock;

use crate::{Canvas, Paint};

/// Widest a glyph can be, in dots.
pub const MAX_GLYPH_WIDTH: usize = 64;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
struct Slot {
    width: u8,
    height: u8,
    offset: u32,
}

/// A bitmap font: dot bitmaps, one per character, with a spacing and line gap.
///
/// Glyphs are proportional (each has its own width) and may differ in height; text
/// is drawn top-aligned from a dot position with [`Canvas::text`].
///
/// # Format
///
/// Fonts are plain text, so they can be written by hand, generated by a script, or
/// loaded at run time with [`Font::parse`]; `include_str!` embeds one at compile time.
///
/// ```text
/// // a comment
/// height 5      // line advance (defaults to the tallest glyph)
/// spacing 1     // dots between glyphs
/// line 1        // dots between lines
///
/// A             // one character, or U+0041; a blank line ends the glyph
/// .#.           // '#' (or @ * X 1) is a dot, '.' (or space - 0 _) is not
/// #.#
/// ###
/// #.#
/// #.#
/// ```
///
/// Glyphs can be added programmatically with [`Font::add`], and [`Font::scale`] makes
/// a larger copy, so one small master gives every size. [`Font::tiny`] is a built-in
/// 3×5 font covering printable ASCII.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Font {
    height: u8,
    spacing: u8,
    line_gap: u8,
    /// Sorted by character.
    glyphs: Vec<(char, Slot)>,
    /// Glyph rows, bit `x` set = dot `x` on.
    rows: Vec<u64>,
}

/// One glyph of a [`Font`].
#[derive(Clone, Copy, Debug)]
pub struct Glyph<'a> {
    /// Width in dots.
    pub width: u8,
    /// Height in dots.
    pub height: u8,
    rows: &'a [u64],
}

impl Glyph<'_> {
    /// Whether dot `(x, y)` of the glyph is set.
    #[inline]
    pub fn dot(&self, x: u8, y: u8) -> bool {
        y < self.height && x < self.width && self.rows[y as usize] >> x & 1 == 1
    }

    /// Row `y` as a bit mask (bit `x` = dot `x`).
    #[inline]
    pub fn row(&self, y: u8) -> u64 {
        self.rows.get(y as usize).copied().unwrap_or(0)
    }
}

/// A parse error, with the 1-based line it was found on.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FontError {
    /// Line number.
    pub line: usize,
    /// What went wrong.
    pub message: &'static str,
}

impl fmt::Display for FontError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "font line {}: {}", self.line, self.message)
    }
}

impl std::error::Error for FontError {}

impl Default for Font {
    fn default() -> Self {
        Self::empty()
    }
}

impl Font {
    /// A font with no glyphs, one dot of spacing and no line gap.
    pub fn empty() -> Self {
        Self { height: 0, spacing: 1, line_gap: 0, glyphs: Vec::new(), rows: Vec::new() }
    }

    /// The built-in 3×5 font (printable ASCII).
    pub fn tiny() -> &'static Font {
        static TINY: OnceLock<Font> = OnceLock::new();
        TINY.get_or_init(|| Font::parse(include_str!("font/tiny.txt")).expect("built-in font"))
    }

    /// Parses the text format described on [`Font`].
    pub fn parse(src: &str) -> Result<Font, FontError> {
        let mut font = Font::empty();
        let mut explicit_height = false;
        let mut lines = src.lines().enumerate().peekable();
        let err = |line: usize, message: &'static str| FontError { line: line + 1, message };
        while let Some((n, line)) = lines.next() {
            let line = line.trim_end();
            if line.is_empty() || line.starts_with("//") {
                continue;
            }
            let mut words = line.split_whitespace();
            let (key, value) = (words.next().unwrap_or(""), words.next());
            match (key, value.and_then(|v| v.parse::<u8>().ok())) {
                ("height", Some(v)) => {
                    font.height = v;
                    explicit_height = true;
                    continue;
                }
                ("spacing", Some(v)) => {
                    font.spacing = v;
                    continue;
                }
                ("line", Some(v)) => {
                    font.line_gap = v;
                    continue;
                }
                ("height" | "spacing" | "line", None) if value.is_some() => return Err(err(n, "expected a number")),
                _ => {}
            }
            let ch = match line.trim().strip_prefix("U+").or_else(|| line.trim().strip_prefix("u+")) {
                Some(hex) => {
                    u32::from_str_radix(hex, 16).ok().and_then(char::from_u32).ok_or(err(n, "bad U+ code point"))?
                }
                None => {
                    let mut chars = line.trim().chars();
                    match (chars.next(), chars.next()) {
                        (Some(c), None) => c,
                        _ => return Err(err(n, "expected a glyph header (one character or U+XXXX) or a keyword")),
                    }
                }
            };
            let mut rows: Vec<u64> = Vec::new();
            let mut width = 0usize;
            while let Some((m, row)) = lines.next_if(|(_, l)| !l.trim().is_empty()) {
                let row = row.trim_end();
                if row.len() > MAX_GLYPH_WIDTH {
                    return Err(err(m, "glyph wider than 64 dots"));
                }
                let mut bits = 0u64;
                for (x, c) in row.chars().enumerate() {
                    match c {
                        '#' | '@' | '*' | 'X' | 'x' | '1' => bits |= 1 << x,
                        '.' | ' ' | '-' | '0' | '_' => {}
                        _ => return Err(err(m, "unexpected character in glyph row")),
                    }
                }
                width = width.max(row.chars().count());
                rows.push(bits);
            }
            if rows.len() > u8::MAX as usize {
                return Err(err(n, "glyph taller than 255 dots"));
            }
            font.insert(ch, width as u8, &rows);
        }
        if !explicit_height {
            font.height = font.glyphs.iter().map(|(_, g)| g.height).max().unwrap_or(0);
        }
        Ok(font)
    }

    /// Adds (or replaces) the glyph for `ch` from rows of `#`/`.` characters, like the
    /// text format. Rows may differ in length; the glyph is as wide as the longest.
    pub fn add(&mut self, ch: char, rows: &[&str]) {
        let bits: Vec<u64> = rows
            .iter()
            .map(|r| {
                r.chars()
                    .take(MAX_GLYPH_WIDTH)
                    .enumerate()
                    .fold(0u64, |b, (x, c)| b | ((!matches!(c, '.' | ' ' | '-' | '0' | '_')) as u64) << x)
            })
            .collect();
        let width = rows.iter().map(|r| r.chars().count().min(MAX_GLYPH_WIDTH)).max().unwrap_or(0) as u8;
        self.insert(ch, width, &bits);
        self.height = self.height.max(bits.len().min(255) as u8);
    }

    fn insert(&mut self, ch: char, width: u8, rows: &[u64]) {
        let slot = Slot { width, height: rows.len().min(255) as u8, offset: self.rows.len() as u32 };
        self.rows.extend_from_slice(&rows[..slot.height as usize]);
        match self.glyphs.binary_search_by_key(&ch, |g| g.0) {
            Ok(i) => self.glyphs[i].1 = slot,
            Err(i) => self.glyphs.insert(i, (ch, slot)),
        }
    }

    /// The glyph for `ch`, if the font has one.
    pub fn glyph(&self, ch: char) -> Option<Glyph<'_>> {
        let i = self.glyphs.binary_search_by_key(&ch, |g| g.0).ok()?;
        let s = self.glyphs[i].1;
        let rows = &self.rows[s.offset as usize..s.offset as usize + s.height as usize];
        Some(Glyph { width: s.width, height: s.height, rows })
    }

    /// Nominal glyph height, in dots.
    pub fn height(&self) -> u8 {
        self.height
    }

    /// Dots between glyphs.
    pub fn spacing(&self) -> u8 {
        self.spacing
    }

    /// Dots between lines.
    pub fn line_gap(&self) -> u8 {
        self.line_gap
    }

    /// Distance from one baseline to the next: `height + line gap`.
    pub fn line_height(&self) -> i32 {
        self.height as i32 + self.line_gap as i32
    }

    /// Number of glyphs.
    pub fn len(&self) -> usize {
        self.glyphs.len()
    }

    /// `true` when the font has no glyphs.
    pub fn is_empty(&self) -> bool {
        self.glyphs.is_empty()
    }

    /// Sets the spacing between glyphs (builder style).
    pub fn with_spacing(mut self, spacing: u8) -> Self {
        self.spacing = spacing;
        self
    }

    /// Sets the gap between lines (builder style).
    pub fn with_line_gap(mut self, gap: u8) -> Self {
        self.line_gap = gap;
        self
    }

    /// Horizontal advance for `ch`: its width plus spacing. Characters the font lacks
    /// advance by the width of the space glyph (or half the height).
    pub fn advance(&self, ch: char) -> i32 {
        let width = match self.glyph(ch).or_else(|| self.glyph(' ')) {
            Some(g) => g.width as i32,
            None => (self.height as i32 / 2).max(1),
        };
        width + self.spacing as i32
    }

    /// Size in dots of `text` when drawn (newlines start new lines).
    pub fn measure(&self, text: &str) -> (i32, i32) {
        let (mut w, mut lines, mut line) = (0, 1, 0);
        for ch in text.chars() {
            if ch == '\n' {
                lines += 1;
                line = 0;
            } else {
                line += self.advance(ch);
                w = w.max(line - self.spacing as i32);
            }
        }
        (w, lines * self.line_height() - self.line_gap as i32)
    }

    /// A copy `n` times larger: every dot becomes an `n × n` block, and spacing,
    /// line gap and height scale with it. Glyphs are capped at 64 dots wide.
    pub fn scale(&self, n: u8) -> Font {
        self.scale_xy(n, n)
    }

    /// A copy scaled `nx` times horizontally and `ny` times vertically: every dot
    /// becomes an `nx × ny` block. A cell is two dots wide and four tall, so
    /// `scale_xy(1, 2)` is what makes a glyph as tall in cells as it is wide.
    pub fn scale_xy(&self, nx: u8, ny: u8) -> Font {
        let (nx, ny) = (nx.max(1) as usize, ny.max(1) as usize);
        let mut out = Font {
            height: (self.height as usize * ny).min(255) as u8,
            spacing: (self.spacing as usize * nx).min(255) as u8,
            line_gap: (self.line_gap as usize * ny).min(255) as u8,
            glyphs: Vec::with_capacity(self.glyphs.len()),
            rows: Vec::with_capacity(self.rows.len() * ny),
        };
        let mut rows = Vec::new();
        for &(ch, s) in &self.glyphs {
            let g = self.glyph(ch).expect("slot");
            rows.clear();
            for y in 0..g.height {
                let mut bits = 0u64;
                for x in 0..(s.width as usize).min(MAX_GLYPH_WIDTH / nx) {
                    if g.dot(x as u8, y) {
                        bits |= ((1u64 << nx) - 1) << (x * nx);
                    }
                }
                for _ in 0..ny {
                    rows.push(bits);
                }
            }
            out.insert(ch, (s.width as usize * nx).min(MAX_GLYPH_WIDTH) as u8, &rows[..rows.len().min(255)]);
        }
        out
    }
}

impl Canvas {
    /// Draws `text` with its top-left corner at dot `(x, y)`. Newlines start a new
    /// line; characters the font lacks leave a space. Returns the size drawn.
    pub fn text(&mut self, x: i32, y: i32, text: &str, font: &Font, paint: impl Into<Paint>) -> (i32, i32) {
        self.shaped(paint.into(), |c, paint| {
            let (mut cx, mut cy) = (x, y);
            for ch in text.chars() {
                if ch == '\n' {
                    cx = x;
                    cy += font.line_height();
                    continue;
                }
                if let Some(g) = font.glyph(ch)
                    && cy < c.height()
                    && cy + g.height as i32 > 0
                    && cx < c.width()
                    && cx + g.width as i32 > 0
                {
                    for row in 0..g.height {
                        let mut bits = g.row(row);
                        // Runs of set bits become spans.
                        while bits != 0 {
                            let start = bits.trailing_zeros();
                            let len = (bits >> start).trailing_ones();
                            c.span(cy + row as i32, cx + start as i32, cx + (start + len) as i32, paint);
                            bits &= u64::MAX.checked_shl(start + len).unwrap_or(0);
                        }
                    }
                }
                cx += font.advance(ch);
            }
        });
        font.measure(text)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Rgb;

    #[test]
    fn tiny_covers_ascii() {
        let f = Font::tiny();
        for c in 32u8..=126 {
            let g = f.glyph(c as char).unwrap_or_else(|| panic!("missing {:?}", c as char));
            assert_eq!(g.height, 5, "{:?}", c as char);
            assert!((1..=3).contains(&g.width), "{:?}", c as char);
        }
        assert_eq!(f.len(), 95);
        assert_eq!(f.height(), 5);
        let a = f.glyph('A').unwrap();
        assert!(a.dot(1, 0) && !a.dot(0, 0) && a.dot(0, 1) && a.dot(2, 4));
        assert_eq!(f.glyph('#').unwrap().row(1), 0b111);
        assert_eq!(f.measure("Hi"), (3 + 1 + 1, 5));
        assert_eq!(f.measure("a\nbc"), (7, 11));
    }

    #[test]
    fn parses_and_reports_errors() {
        let f = Font::parse("spacing 2\nline 3\n\nU+0041\n#.\n.#\n\n.\n#\n\n// c\nx\n1\n").unwrap();
        assert_eq!((f.spacing(), f.line_gap(), f.height()), (2, 3, 2));
        assert_eq!(f.glyph('A').unwrap().row(1), 0b10);
        assert_eq!(f.glyph('.').unwrap().width, 1);
        assert!(f.glyph('x').unwrap().dot(0, 0));
        assert_eq!(f.advance('?'), f.advance('.'));
        assert_eq!(Font::parse("A\n#?\n").unwrap_err().line, 2);
        assert_eq!(Font::parse("hello world\n").unwrap_err().line, 1);
        assert_eq!(Font::parse("height x\n").unwrap_err().line, 1);
        assert!(Font::parse("U+ZZ\n#\n").is_err());
        assert!(Font::parse("").unwrap().is_empty());
    }

    #[test]
    fn add_and_scale() {
        let mut f = Font::empty();
        f.add('o', &["##", "##"]);
        assert_eq!(f.glyph('o').unwrap().row(0), 0b11);
        let big = f.scale(3);
        let g = big.glyph('o').unwrap();
        assert_eq!((g.width, g.height), (6, 6));
        assert_eq!(g.row(5), 0b111111);
        assert_eq!(big.height(), 6);
        assert_eq!(big.spacing(), 3);
        let tall = f.scale_xy(1, 2);
        let g = tall.glyph('o').unwrap();
        assert_eq!((g.width, g.height, tall.spacing(), tall.height()), (2, 4, 1, 4));
        f.add('o', &["#"]);
        assert_eq!(f.glyph('o').unwrap().width, 1);
        assert_eq!(f.len(), 1);
    }

    #[test]
    fn draws_text() {
        let mut c = Canvas::new(3, 2);
        let size = c.text(0, 0, "I", Font::tiny(), Rgb::hex(0xffffff));
        assert_eq!(size, (3, 5));
        assert_eq!(c.to_text(), "⢹⠁⠀\n⠉⠁⠀\n");
        let mut c = Canvas::new(3, 2);
        c.text(-1, 6, "II", Font::tiny(), Rgb::hex(0xffffff));
        assert!(c.get(0, 6).is_some() && c.get(5, 6).is_some() && c.get(0, 7).is_some() && c.get(4, 7).is_some());
        let mut e = Canvas::new(3, 2);
        e.fill_rect(0.0, 0.0, 6.0, 8.0, 0xffffffu32);
        e.text(0, 0, "I", Font::tiny(), Paint::erase());
        assert!(e.get(0, 0).is_none() && e.get(0, 1).is_some());
    }
}
